# Generated by Django 4.2.7 on 2025-12-13 14:32

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lesson_video_upload_path, verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='YouTube linki'),
        ),
    ]
