# Generated by Django 4.2.7 on 2025-12-14 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_fix_module_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson'),
        ),
        migrations.CreateModel(
            name='ListeningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('audio_file', models.FileField(upload_to='listening_audios/', verbose_name='Audio fayl')),
                ('listening_type', models.CharField(choices=[('one_choice', 'One Choice'), ('two_choice', 'Two Choice'), ('three_choice', 'Three Choice'), ('matching', 'Matching'), ('gap_filling', 'Gap Filling'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True or False'), ('true_false_not_given', 'True or False or Not Given')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timer_minutes', models.IntegerField(default=0, help_text='0 yozilsa timer ishlamaydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_lessons', to='courses.module')),
            ],
            options={
                'verbose_name': 'Listening darsi',
                'verbose_name_plural': 'Listening darslari',
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='listening_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.listeninglesson'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson'), ('user', 'listening_lesson')},
        ),
    ]
