# Generated by Django 4.2.7 on 2025-12-14 19:51

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_userprogress_lesson_listeninglesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapFillingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_with_gaps', models.TextField(help_text="Matn bo'sh joylar bilan: (a) ______")),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='listeninglesson',
            name='audio_file',
            field=models.FileField(upload_to=courses.models.listening_audio_upload_path, verbose_name='Audio fayl'),
        ),
        migrations.AlterField(
            model_name='listeninglesson',
            name='description',
            field=models.TextField(blank=True, help_text="Listening mazmuni, ko'rsatmalar"),
        ),
        migrations.AlterField(
            model_name='listeninglesson',
            name='listening_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('matching', 'Matching'), ('gap_filling', 'Gap Filling'), ('true_false_not_given', 'True/False/Not Given')], max_length=50),
        ),
        migrations.CreateModel(
            name='TrueFalseNotGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('correct_answer', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('not_given', 'Not Given')], max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='Javob tushuntirishi')),
                ('order', models.IntegerField(default=0)),
                ('listening_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfng_questions', to='courses.listeninglesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField()),
                ('column_a', models.TextField(help_text='Birinchi ustun elementlari, qatorlar bilan ajratilgan')),
                ('column_b', models.TextField(help_text='Ikkinchi ustun elementlari, qatorlar bilan ajratilgan')),
                ('correct_matches', models.TextField(help_text="To'g'ri moslamalar JSON formatda: {'1':'A','2':'B'}")),
                ('order', models.IntegerField(default=0)),
                ('listening_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_questions', to='courses.listeninglesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('listening_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.listeninglesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('option_letter', models.CharField(default='A', max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.listeningquestion')),
            ],
            options={
                'ordering': ['option_letter'],
            },
        ),
        migrations.CreateModel(
            name='GapOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_letter', models.CharField(max_length=2)),
                ('correct_word', models.CharField(max_length=200)),
                ('options', models.TextField(help_text='Variantlar vergul bilan ajratilgan: goes,went,was going,is going')),
                ('gap_filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.gapfillingquestion')),
            ],
            options={
                'ordering': ['gap_letter'],
            },
        ),
        migrations.AddField(
            model_name='gapfillingquestion',
            name='listening_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_fillings', to='courses.listeninglesson'),
        ),
    ]
