# Generated by Django 4.2.7 on 2025-12-15 21:12

import courses.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_gapfillingquestion_alter_listeninglesson_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('speaking_type', models.CharField(choices=[('question_answer', 'Savol-Javob'), ('topic_discussion', "Mavzu bo'yicha nutq"), ('role_play', 'Role Play'), ('picture_description', 'Rasm tasviri'), ('story_telling', 'Hikoya qilish')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('instruction_text', models.TextField(help_text="Studentga ko'rsatma")),
                ('example_text', models.TextField(blank=True, help_text='Namuna javob')),
                ('target_duration', models.IntegerField(default=60, help_text='Maqsadli davomiylik (soniya)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_lessons', to='courses.module')),
            ],
            options={
                'verbose_name': 'Speaking darsi',
                'verbose_name_plural': 'Speaking darslari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('hints', models.TextField(blank=True, help_text="Yordamchi so'zlar/iboralar")),
                ('order', models.IntegerField(default=0)),
                ('speaking_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.speakinglesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=courses.models.speaking_audio_upload_path, verbose_name='Audio fayl')),
                ('transcript', models.TextField(blank=True, help_text='STT natijasi')),
                ('fluency_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vocabulary_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grammar_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pronunciation_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField(blank=True, help_text='AI tahlili')),
                ('suggestions', models.TextField(blank=True, help_text='Takliflar')),
                ('duration', models.IntegerField(default=0, help_text='Davomiylik (soniya)')),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaking_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.speakinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
