# Generated by Django 4.2.7 on 2025-12-15 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_speakinglesson_speakingquestion_speakingattempt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'listening_lesson'), ('user', 'lesson')},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='speaking_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.speakinglesson'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'speaking_lesson'), ('user', 'listening_lesson'), ('user', 'lesson')},
        ),
    ]
