# Generated by Django 4.2.7 on 2025-12-19 13:22

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_userprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reading_type', models.CharField(choices=[('sentence_completion', 'Sentence Completion'), ('matching_headings', 'Matching Headings'), ('short_answer', 'Short-Answer Questions'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('multiple_choice', 'Multiple Choice'), ('diagram_completion', 'Diagram/Flow-chart/Table Completion'), ('summary_completion', 'Summary Completion')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Birinchi (4.0-5.0)'), ('intermediate', 'Ikkinchi (5.0-6.0)'), ('advanced', 'Uchinchi (6.0-7.5)')], default='beginner', max_length=20)),
                ('description', models.TextField(help_text="Reading matni yoki ko'rsatmalar")),
                ('reading_text', models.TextField(help_text='Asosiy reading matni')),
                ('instruction', models.TextField(help_text="Talaba uchun ko'rsatmalar")),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to=courses.models.reading_image_upload_path, verbose_name='Diagramma/rasm')),
                ('timer_minutes', models.IntegerField(default=20, help_text='Vaqt chegarasi (daqiqa)')),
                ('word_count', models.IntegerField(default=0, help_text="Matndagi so'zlar soni")),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lessons', to='courses.module')),
            ],
            options={
                'verbose_name': 'Reading darsi',
                'verbose_name_plural': 'Reading darslari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('sentence_completion', 'Sentence Completion'), ('matching_headings', 'Matching Headings'), ('short_answer', 'Short-Answer Questions'), ('true_false_not_given', 'True/False/Not Given'), ('yes_no_not_given', 'Yes/No/Not Given'), ('multiple_choice', 'Multiple Choice'), ('diagram_completion', 'Diagram/Flow-chart/Table Completion'), ('summary_completion', 'Summary Completion')], max_length=50)),
                ('marks', models.IntegerField(default=1, help_text='Ball')),
                ('order', models.IntegerField(default=0)),
                ('reading_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.readinglesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='Javob tushuntirishi')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.readingquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'listening_lesson'), ('user', 'speaking_lesson'), ('user', 'lesson')},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='reading_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_user_progress', to='courses.readinglesson'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'listening_lesson'), ('user', 'speaking_lesson'), ('user', 'lesson'), ('user', 'reading_lesson')},
        ),
        migrations.CreateModel(
            name='UserReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Sarflangan vaqt (soniya)')),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_user_progress', to='courses.readinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading progress',
                'verbose_name_plural': 'Reading progresslar',
                'unique_together': {('user', 'reading_lesson')},
            },
        ),
    ]
