# Generated by Django 4.2.7 on 2025-12-19 13:44

import courses.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_readinglesson_readingquestion_readinganswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writing_type', models.CharField(choices=[('task1_academic', 'Task 1 (Academic)'), ('task1_general', 'Task 1 (General)'), ('task2', 'Task 2'), ('essay', 'Essay'), ('letter', 'Letter'), ('report', 'Report')], max_length=50)),
                ('task_type', models.CharField(blank=True, choices=[('opinion', 'Opinion Essay'), ('discussion', 'Discussion Essay'), ('problem_solution', 'Problem-Solution'), ('advantages_disadvantages', 'Advantages-Disadvantages'), ('two_part', 'Two-part Question')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Birinchi (4.0-5.0)'), ('intermediate', 'Ikkinchi (5.0-6.0)'), ('advanced', 'Uchinchi (6.0-7.5)')], default='beginner', max_length=20)),
                ('description', models.TextField(help_text="Writing vazifasi haqida ma'lumot")),
                ('task_text', models.TextField(help_text='Writing vazifa matni')),
                ('instruction', models.TextField(help_text="Talaba uchun ko'rsatmalar")),
                ('example_image', models.ImageField(blank=True, null=True, upload_to=courses.models.writing_image_upload_path, verbose_name='Namuna diagramma/rasm')),
                ('word_count_min', models.IntegerField(default=150, help_text="Minimal so'zlar soni")),
                ('word_count_max', models.IntegerField(default=250, help_text="Maksimal so'zlar soni")),
                ('timer_minutes', models.IntegerField(default=60, help_text='Vaqt chegarasi (daqiqa)')),
                ('criteria_content', models.IntegerField(default=25, help_text='Content uchun ball (0-100)')),
                ('criteria_coherence', models.IntegerField(default=25, help_text='Coherence uchun ball (0-100)')),
                ('criteria_vocabulary', models.IntegerField(default=25, help_text='Vocabulary uchun ball (0-100)')),
                ('criteria_grammar', models.IntegerField(default=25, help_text='Grammar uchun ball (0-100)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_lessons', to='courses.module')),
            ],
            options={
                'verbose_name': 'Writing darsi',
                'verbose_name_plural': 'Writing darslari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WritingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Foydalanuvchi javobi')),
                ('word_count', models.IntegerField(default=0)),
                ('content_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coherence_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vocabulary_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grammar_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField(blank=True, help_text='AI tahlili')),
                ('suggestions', models.TextField(blank=True, help_text='Takliflar')),
                ('time_spent', models.IntegerField(default=0, help_text='Sarflangan vaqt (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_attempts', to=settings.AUTH_USER_MODEL)),
                ('writing_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.writinglesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'reading_lesson'), ('user', 'lesson'), ('user', 'speaking_lesson'), ('user', 'listening_lesson')},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='writing_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_user_progress', to='courses.writinglesson'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson'), ('user', 'listening_lesson'), ('user', 'writing_lesson'), ('user', 'reading_lesson'), ('user', 'speaking_lesson')},
        ),
        migrations.CreateModel(
            name='UserWritingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Jami sarflangan vaqt (soniya)')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_progress', to=settings.AUTH_USER_MODEL)),
                ('writing_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_user_progress', to='courses.writinglesson')),
            ],
            options={
                'verbose_name': 'Writing progress',
                'verbose_name_plural': 'Writing progresslar',
                'unique_together': {('user', 'writing_lesson')},
            },
        ),
    ]
